title: Epiroc Safety
description: Website about Epiroc Corporation safety
url: https://catosoriginal.github.io
baseurl: /epiroc-safety/
author: catosoriginal
email: catos@catosmail.slmail.me

layouts_dir: backend/jekyll/_layouts
includes_dir: backend/jekyll/_includes

exclude:
 - github
defaults:
  - scope:
      path: "" 
    values:
      layout: default
      title: "Epiroc Safety"
      icon: /epiroc-safety/backend/assets/icons/epiroc-logo-yellow-icon-nobg.png
  - scope:
      path: "home.html"
    values:
      title: "Home"
      loadmd: "/epiroc-safety/backend/jekyll/_includes/markdowns/home.md"
  - scope:
      path: "index.html"
    values:
      title: "Wait"
  - scope:
      path: "verify-work.html"
    values:
      title: "Verify Work"
      icon: /epiroc-safety/backend/assets/icons/verified.ico
      