title: Epiroc Safety
description: Website about EPIROC INC. safety
url: https://catosoriginal.github.io
baseurl: /epiroc-safety/
author: catosoriginal
email: catos@catosmail.slmail.me

layouts_dir: "{{ 'backend/jekyll/_layouts' | relative_url }}"
includes_dir: "{{ 'backend/jekyll/_includes' | relative_url }}"

exclude:
 - github
defaults:
  - scope:
      path: "" 
    values:
      layout: default
      title: "Epiroc Safety"
      icon: "{{ '/backend/assets/icons/epiroc-logo-yellow-icon-nobg.png' | relative_url }}"
  - scope:
      path: "home.html"
    values:
      title: "Home"
  - scope:
      path: "index.html"
    values:
      title: "Wait"
  - scope:
      path: "verify-work.html"
    values:
      title: "Verify Work"
      icon: "{{ 'backend/assets/icons/verified.ico' | relative_url }}"
      