title: Epiroc Safety
description: Website about EPIROC INC. safety
baseurl: "/epiroc-safety"
author: catosoriginal
email: catos@catosmail.slmail.me

layouts_dir: backend/jekyll/_layouts
includes_dir: backend/jekyll/_includes

exclude:
 - github

defaults:
  - scope:
      path: "" 
    values:
      layout: default
      title: "Epiroc Safety"
      icon: "backend/assets/icons/epiroc-logo-yellow-icon-nobg.png"
  - scope:
      path: "epiroc-safety/home"
    values:
      title: "Home"
  - scope:
      path: "epiroc-safety/index"
    values:
      title: "Wait"